export Badge from './Badge/Badge'
export Copyright from './Copyright/Copyright'
export Logo from './Logo/Logo'
export Privacy from './Privacy/Privacy'
export Terms from './Terms/Terms'
export Wordmark from './Wordmark/Wordmark'
